Repository scherzma/Skunk, pull requests merged in 2024-06, with the labels that each got.

#40 Implement P2P Network Messaging and Chat Features
  .gitignore
  .idea/.gitignore
  cmd/main.go
  cmd/skunk/adapter/in/networkMockAdapter/networkMockAdapter.go
  cmd/skunk/adapter/out/frontend/mockFrontend/mockFrontendAdapter.go
  cmd/skunk/adapter/out/storage/storageSQLiteAdapter/StorageSQLiteAdapter.go
  cmd/skunk/application/domain/chat/c_service/chatApp.go
  cmd/skunk/application/domain/chat/c_service/chatService.go
  cmd/skunk/application/domain/chat/chatLogicInterface.go
  cmd/skunk/application/domain/p2p_network/networkLogicInterface.go
  cmd/skunk/application/domain/p2p_network/p_model/.keep
  cmd/skunk/application/domain/p2p_network/p_model/networkChatMessageRepository.go
  cmd/skunk/application/domain/p2p_network/p_model/networkChatRepository.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/chatToNetwork.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/inviteToChatHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/joinChatHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/leaveChatHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/messageSender.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/peer.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/sendFileHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/sendMessageHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/setUsernameHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/syncRequestHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/messageHandlers/syncResponseHandler.go
  cmd/skunk/application/domain/p2p_network/p_service/networkChatService.go
  cmd/skunk/application/domain/p2p_network/p_service/networkPeerManager.go
  cmd/skunk/application/domain/p2p_network/p_service/securityService.go
  cmd/skunk/application/port/frontend/frontendPort.go
  cmd/skunk/application/port/network/networkInteractionPort.go
  cmd/skunk/application/port/store/storagePort.go
  cmd/skunk/application/port/store/storePeerPort.go
  go.mod
  go.sum
  test/inviteToChat_test.go
  test/joinChat_test.go
  test/leaveChat_test.go
  test/mockChatLogic.go
  test/networkChatMessageRepository_test.go
  test/peerNetworkConnection_test.go
  test/sendMessage_test.go
  test/setUsername_test.go
  test/storageSQLiteAdapter_test.go
  test/syncRequest_test.go
  test/syncResponse_test.go
Labels: high

#41 removed .idea
  .idea/.gitignore
Labels: low

#42 Implementation of the Frontend
  cmd/main.go
  cmd/skunk/adapter/in/frontend/frontend.go
  cmd/skunk/adapter/in/frontendAdapter/frontendAdapter.go
  cmd/skunk/adapter/in/networkMockAdapter/networkMockAdapter.go
  go.mod
  go.sum
  test/frontend_test.go
Labels: critical
